extends: 
  - stylelint-config-rational-order
plugins:
  - stylelint-color-format
rules:
  color-format/format:
    format: hsl
  plugin/rational-order:
    - true
    - empty-line-between-groups: true